"""add raw_raga_name and raw_composer_name to Song

Revision ID: 0694ef20e306
Revises: b9a4a8fc1fe6
Create Date: 2025-07-11 08:10:25.899673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0694ef20e306'
down_revision = 'b9a4a8fc1fe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raga_composer')
    op.drop_table('raga_artist')
    op.add_column('songs', sa.Column('raw_raga_name', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('raw_composer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'raw_composer_name')
    op.drop_column('songs', 'raw_raga_name')
    op.create_table('raga_artist',
    sa.Column('raga_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='raga_artist_artist_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raga_id'], ['ragas.id'], name='raga_artist_raga_id_fkey', ondelete='CASCADE')
    )
    op.create_table('raga_composer',
    sa.Column('raga_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('composer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], name='raga_composer_composer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raga_id'], ['ragas.id'], name='raga_composer_raga_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
