"""Add Composer model and raga_composer association table

Revision ID: 06ee979a85a6
Revises: 9ce3dccd7df3
Create Date: 2025-07-08 00:17:11.688038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ee979a85a6'
down_revision = '9ce3dccd7df3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('era', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composers_id'), 'composers', ['id'], unique=False)
    op.create_index(op.f('ix_composers_name'), 'composers', ['name'], unique=True)
    op.create_table('raga_composer',
    sa.Column('raga_id', sa.Integer(), nullable=True),
    sa.Column('composer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raga_id'], ['ragas.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raga_composer')
    op.drop_index(op.f('ix_composers_name'), table_name='composers')
    op.drop_index(op.f('ix_composers_id'), table_name='composers')
    op.drop_table('composers')
    # ### end Alembic commands ###
