"""Expand schema: full Song, Tala, richer relationships and fields

Revision ID: 29f9c03ef636
Revises: a371e9aedd11
Create Date: 2025-07-09 22:25:56.230229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f9c03ef636'
down_revision = 'a371e9aedd11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('english_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talas_id'), 'talas', ['id'], unique=False)
    op.create_index(op.f('ix_talas_name'), 'talas', ['name'], unique=True)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('composer_id', sa.Integer(), nullable=True),
    sa.Column('raga_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('tala_id', sa.Integer(), nullable=True),
    sa.Column('audio_sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audio_sample_id'], ['audio_samples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raga_id'], ['ragas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tala_id'], ['talas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.add_column('artists', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('death_year', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('genres', sa.String(length=200), nullable=True))
    op.add_column('audio_samples', sa.Column('song_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audio_samples', 'songs', ['song_id'], ['id'], ondelete='SET NULL')
    op.add_column('composers', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('composers', sa.Column('death_year', sa.Integer(), nullable=True))
    op.add_column('performances', sa.Column('tala_id', sa.Integer(), nullable=True))
    op.add_column('performances', sa.Column('song_id', sa.Integer(), nullable=True))
    op.add_column('performances', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('performances', sa.Column('rating', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'performances', 'talas', ['tala_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'performances', 'songs', ['song_id'], ['id'], ondelete='SET NULL')
    op.add_column('ragas', sa.Column('parent_raga_id', sa.Integer(), nullable=True))
    op.add_column('ragas', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('ragas', sa.Column('tala_id', sa.Integer(), nullable=True))
    op.add_column('ragas', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('ragas', sa.Column('origin', sa.String(length=100), nullable=True))
    op.add_column('ragas', sa.Column('language', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'ragas', 'ragas', ['parent_raga_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ragas', 'talas', ['tala_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ragas', 'types', ['type_id'], ['id'], ondelete='SET NULL')
    op.add_column('types', sa.Column('english_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types', 'english_name')
    op.drop_constraint(None, 'ragas', type_='foreignkey')
    op.drop_constraint(None, 'ragas', type_='foreignkey')
    op.drop_constraint(None, 'ragas', type_='foreignkey')
    op.drop_column('ragas', 'language')
    op.drop_column('ragas', 'origin')
    op.drop_column('ragas', 'region')
    op.drop_column('ragas', 'tala_id')
    op.drop_column('ragas', 'type_id')
    op.drop_column('ragas', 'parent_raga_id')
    op.drop_constraint(None, 'performances', type_='foreignkey')
    op.drop_constraint(None, 'performances', type_='foreignkey')
    op.drop_column('performances', 'rating')
    op.drop_column('performances', 'duration')
    op.drop_column('performances', 'song_id')
    op.drop_column('performances', 'tala_id')
    op.drop_column('composers', 'death_year')
    op.drop_column('composers', 'birth_year')
    op.drop_constraint(None, 'audio_samples', type_='foreignkey')
    op.drop_column('audio_samples', 'song_id')
    op.drop_column('artists', 'genres')
    op.drop_column('artists', 'death_year')
    op.drop_column('artists', 'birth_year')
    op.drop_index(op.f('ix_talas_name'), table_name='talas')
    op.drop_index(op.f('ix_talas_id'), table_name='talas')
    op.drop_table('talas')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
