"""Add data column to AudioSample for binary audio

Revision ID: 92bea288f5f6
Revises: 97307ed122ea
Create Date: 2025-07-08 00:38:12.897933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bea288f5f6'
down_revision = '97307ed122ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_samples', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_samples', 'data')
    # ### end Alembic commands ###
