"""Add type_id to Performance and Song

Revision ID: 97307ed122ea
Revises: e7c014ffcce4
Create Date: 2025-07-08 00:34:17.314082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97307ed122ea'
down_revision = 'e7c014ffcce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performances', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'performances', 'types', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performances', type_='foreignkey')
    op.drop_column('performances', 'type_id')
    # ### end Alembic commands ###
