"""Initial schema for RagaSense

Revision ID: 9ce3dccd7df3
Revises: 
Create Date: 2025-07-07 23:02:46.809333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ce3dccd7df3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('era', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=True)
    op.create_table('ragas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alternate_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tradition', sa.String(length=50), nullable=True),
    sa.Column('arohana', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avarohana', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('characteristic_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vadi', sa.String(length=20), nullable=True),
    sa.Column('samvadi', sa.String(length=20), nullable=True),
    sa.Column('varjya_swaras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jati', sa.String(length=50), nullable=True),
    sa.Column('time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('season', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rasa', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mood', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('notable_compositions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pitch_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tonic_frequency', sa.String(length=20), nullable=True),
    sa.Column('pakad', sa.Text(), nullable=True),
    sa.Column('thaat', sa.String(length=50), nullable=True),
    sa.Column('melakarta_number', sa.Integer(), nullable=True),
    sa.Column('carnatic_equivalent', sa.String(length=100), nullable=True),
    sa.Column('hindustani_equivalent', sa.String(length=100), nullable=True),
    sa.Column('chakra', sa.String(length=50), nullable=True),
    sa.Column('janya_ragas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ragas_id'), 'ragas', ['id'], unique=False)
    op.create_index(op.f('ix_ragas_melakarta_number'), 'ragas', ['melakarta_number'], unique=False)
    op.create_index(op.f('ix_ragas_name'), 'ragas', ['name'], unique=True)
    op.create_index(op.f('ix_ragas_thaat'), 'ragas', ['thaat'], unique=False)
    op.create_index(op.f('ix_ragas_tradition'), 'ragas', ['tradition'], unique=False)
    op.create_table('audio_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('audio_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raga_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raga_id'], ['ragas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_samples_id'), 'audio_samples', ['id'], unique=False)
    op.create_table('raga_artist',
    sa.Column('raga_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raga_id'], ['ragas.id'], ondelete='CASCADE')
    )
    op.create_table('performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('raga_id', sa.Integer(), nullable=True),
    sa.Column('audio_sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['audio_sample_id'], ['audio_samples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raga_id'], ['ragas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performances_id'), 'performances', ['id'], unique=False)
    #op.drop_table('raga_relationships')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raga_relationships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('raga_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_raga_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relationship_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='raga_relationships_pkey')
    )
    op.drop_index(op.f('ix_performances_id'), table_name='performances')
    op.drop_table('performances')
    op.drop_table('raga_artist')
    op.drop_index(op.f('ix_audio_samples_id'), table_name='audio_samples')
    op.drop_table('audio_samples')
    op.drop_index(op.f('ix_ragas_tradition'), table_name='ragas')
    op.drop_index(op.f('ix_ragas_thaat'), table_name='ragas')
    op.drop_index(op.f('ix_ragas_name'), table_name='ragas')
    op.drop_index(op.f('ix_ragas_melakarta_number'), table_name='ragas')
    op.drop_index(op.f('ix_ragas_id'), table_name='ragas')
    op.drop_table('ragas')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
