"""Expand Raga model with JSONB and new fields

Revision ID: 9eee97c6b6ff
Revises: 92bea288f5f6
Create Date: 2025-07-08 00:44:53.263956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eee97c6b6ff'
down_revision = '92bea288f5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
