"""Add composer_id to Performance

Revision ID: a371e9aedd11
Revises: a6e47cd616ad
Create Date: 2025-07-09 09:34:59.723954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a371e9aedd11'
down_revision = 'a6e47cd616ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performances', sa.Column('composer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'performances', 'composers', ['composer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performances', type_='foreignkey')
    op.drop_column('performances', 'composer_id')
    # ### end Alembic commands ###
