"""Add English map tables for raga, type, tala

Revision ID: a6e47cd616ad
Revises: 9eee97c6b6ff
Create Date: 2025-07-08 00:51:05.912541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e47cd616ad'
down_revision = '9eee97c6b6ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
