"""add region column to all main tables

Revision ID: b9a4a8fc1fe6
Revises: 29f9c03ef636
Create Date: 2025-07-10 22:14:08.694007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a4a8fc1fe6'
down_revision = '29f9c03ef636'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('region', sa.String(), nullable=True))
    op.add_column('audio_samples', sa.Column('region', sa.String(), nullable=True))
    op.add_column('composers', sa.Column('region', sa.String(), nullable=True))
    op.add_column('performances', sa.Column('region', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('region', sa.String(), nullable=True))
    op.add_column('talas', sa.Column('region', sa.String(), nullable=True))
    op.add_column('types', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types', 'region')
    op.drop_column('talas', 'region')
    op.drop_column('songs', 'region')
    op.drop_column('performances', 'region')
    op.drop_column('composers', 'region')
    op.drop_column('audio_samples', 'region')
    op.drop_column('artists', 'region')
    # ### end Alembic commands ###
