labels:
  # Priority Labels
  - name: "priority: critical"
    color: "d73a4a"
    description: "Critical issues that need immediate attention"
  - name: "priority: high"
    color: "fbca04"
    description: "High priority issues"
  - name: "priority: medium"
    color: "0e8a16"
    description: "Medium priority issues"
  - name: "priority: low"
    color: "0075ca"
    description: "Low priority issues"

  # Type Labels
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"

  # Component Labels
  - name: "frontend"
    color: "1d76db"
    description: "Frontend related issues"
  - name: "backend"
    color: "0e8a16"
    description: "Backend related issues"
  - name: "ml"
    color: "fbca04"
    description: "Machine learning related issues"
  - name: "raga-detection"
    color: "d93f0b"
    description: "Raga detection specific issues"
  - name: "ui/ux"
    color: "c2e0c6"
    description: "User interface and experience issues"
  - name: "performance"
    color: "ffa500"
    description: "Performance related issues"
  - name: "security"
    color: "d73a4a"
    description: "Security related issues"

  # Status Labels
  - name: "needs-triage"
    color: "fbca04"
    description: "Issues that need to be reviewed"
  - name: "in-progress"
    color: "1d76db"
    description: "Work in progress"
  - name: "blocked"
    color: "d73a4a"
    description: "Blocked by other issues"
  - name: "ready for review"
    color: "0e8a16"
    description: "Ready for code review"
  - name: "approved"
    color: "28a745"
    description: "Approved for merge"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"

  # Platform Labels
  - name: "platform: web"
    color: "1d76db"
    description: "Web platform specific"
  - name: "platform: ios"
    color: "000000"
    description: "iOS platform specific"
  - name: "platform: android"
    color: "3ddc84"
    description: "Android platform specific"

  # Special Labels
  - name: "breaking-change"
    color: "d73a4a"
    description: "Breaking changes"
  - name: "hotfix"
    color: "d73a4a"
    description: "Critical bug fixes"
  - name: "feature-request"
    color: "a2eeef"
    description: "New feature requests"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
