blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: RagaSense Documentation
    url: https://github.com/your-username/raga_detector/wiki
    about: Check our documentation for answers.
